""" This module contains various static variables that can be changed based on the project. The other classes might
make use of the variables in this module."""
root_group = '_RIG'
control_group = 'CTRL'
joint_group = 'JOINTS'
ik_group = 'IK'
geo_group = 'GEO'
default_control = 'cube'
controller_templates = '__templates__'
fk = 'fk'
ik = 'ik'
joints = 'joints'
ik_handle = 'ikHandle'
control = 'ctrl'
offset = 'offset'
leg = 'leg'
left = 'l'
right = 'r'
hip = 'hip'
knee = 'knee'
ankle = 'ankle'
